language: python
python:
- '2.7'

before_install:
- pip install traceback2==1.4.0
- pip install -r test_requirements.txt -i https://testpypi.python.org/pypi

install:
    - python setup.py install

script: python setup.py sdist --format zip