language: python
python:
- '2.7'

branches:
  only:
    - dev
	
before_install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt

install:
    - python setup.py install

script: python setup.py sdist --format zip
